#!/bin/sh
# display current brightness

# get first two digits of brightness value
brightnum=$(xbacklight -get)
brightness=$(printf "${brightnum%.*}")

if [[ "$brightness" -gt "70" ]]; then
	echo "💡 $brightness"
elif [[ "$brightness" -lt "30" ]]; then
	echo "💡 $brightness"
else
	echo "💡 $brightness"
fi
